/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.redscarf.distributedsystems.synchronization;

import com.github.redscarf.distributedsystems.synchronization.threads.MyThreadFactory;

public class App {
    public static void main(String[] args) {
        MyThreadFactory factory = new MyThreadFactory();
        
        Thread thread1 = factory.createMyThread();
        Thread thread2 = factory.createMyThread();
        
        thread1.start();
        thread2.start();
    }
}
